### ISSUE TITLE
Removing .htaccess broke production CORS

### ISSUE THREAD

**Issue by pboyd04** [BurningFlipside/Profiles#24]
I'm not sure why but removing the .htaccess file from api/v1 broke CORS and therefore some production code. We should figure out why before repushing this change...

**Comment by russelltsherman** [comment]
when you tested this deployment did you add the site urls to the settings class?
the dynamic cors code would need that in order to allow the connection

**Comment by russelltsherman** [comment]
could it be the trailing slashes in the default paths in
profiles/api/v1/index.php ?

**Comment by russelltsherman** [comment]
I'm thinking this PR can solve this issue
https://github.com/BurningFlipside/Profiles/pull/25

**Comment by pboyd04** [comment]
Fixed by https://github.com/BurningFlipside/CommonCode/pull/54
