### ISSUE TITLE
notice message on user registration confirmation

### ISSUE THREAD

**Issue by russelltsherman** [BurningFlipside/Profiles#26]
when user follows link from registration email the following notices are displayed..

Notice: Undefined property: stdClass::$sn in /var/www/common/Auth/class.SQLPendingUser.php on line 21

Notice: Undefined property: stdClass::$sn in /var/www/common/Auth/class.SQLPendingUser.php on line 25

Notice: Undefined property: stdClass::$block in /var/www/common/Auth/class.SQLPendingUser.php on line 21

Notice: Undefined property: stdClass::$block in /var/www/common/Auth/class.SQLPendingUser.php on line 25

Notice: Undefined property: stdClass::$block in /var/www/common/Auth/class.SQLPendingUser.php on line 21

Notice: Undefined property: stdClass::$block in /var/www/common/Auth/class.SQLPendingUser.php on line 25

**Comment by pboyd04** [comment]
Fixed

**Comment by russelltsherman** [comment]
which pull request fixes this?

**Comment by pboyd04** [comment]
Commit's here: https://github.com/BurningFlipside/CommonCode/commit/76bac33910ebbe0eac97d06a743ff0ab2d9135aa

**Comment by pboyd04** [comment]
Sorry, I just fixed it on production rather than going through a pull.
