### ISSUE TITLE
user registration email does not include FQDN in link

### ISSUE THREAD

**Issue by russelltsherman** [BurningFlipside/Profiles#27]
![uploads/c2b46a1f-8cee-43b9-a0c3-d7fb662f6762/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fc2b46a1f-8cee-43b9-a0c3-d7fb662f6762%2Fblob)

**Comment by pboyd04** [comment]
I've hardcoded production to the correct URL for right now. I'm not sure why the profilesUrl is not working correctly right now.
