### ISSUE TITLE
500 error on password reset

### ISSUE THREAD

**Issue by russelltsherman** [BurningFlipside/Profiles#57]
visit: https://profiles.burningflipside.com/reset.php
select forgot password
enter username
submit 
UI shows no response

console shows 500 error
<img width="819" alt="screenshot 2017-12-12 16 59 51" src="https://user-images.githubusercontent.com/24982262/33913108-17138678-df5e-11e7-96bf-2113d4cf0361.png">

**Comment by pboyd04** [comment]
Fixed in #58
