### ISSUE TITLE
Remove "select user" menu from individual profile listing

### ISSUE THREAD

**Issue by adamjrice** [BurningFlipside/Profiles#60]
When loading `https://profiles.burningflipside.com/_admin/user_edit.php?uid=foo`, the page is loading a list of all users. With over 7,000 users, this significantly slows down page loading.

**Comment by treg** [comment]
Default filtering?

How about:

All accounts that attended last event + new accounts since then?

Add filterBy fields?

**Comment by adamjrice** [comment]
I just don't think that popup menu is very useful. Even if there were only 100 candidates, you wouldn't want to trawl through a popup to find the one you're looking for.

**Comment by treg** [comment]
What I was thinking was not  popup but blank criteria fields.  The results
table is only populated after a search button is clicked. Also a check box
that would indicate an exhaustive search or just last attended+new .

**Comment by adamjrice** [comment]
I see what you're saying. We've already got a catch-all search box on the listings page, which I use a lot; faceted search would be cool, but I don't see a huge need for it.

**Comment by adamjrice** [comment]
Cool!
