### ISSUE TITLE
Cache user listing

### ISSUE THREAD

**Issue by adamjrice** [BurningFlipside/Profiles#61]
When loading `https://profiles.burningflipside.com/_admin/users_current.php`, the page loads the full listing of users. Ideally this would be cached so that when navigating between detail pages and the list page, the full listing did not need to be reloaded.

**Comment by pboyd04** [comment]
@adamjrice The website has the fix for this right now. It will cache the data for up to 2 minutes assuming your browser supports localStorage. Does that work for you?

**Comment by adamjrice** [comment]
@pboyd04 Hard to say. There's a delay of a few beats when navigating back to the list, but that might be a performance issue, not a bandwidth issue.

**Comment by pboyd04** [comment]
I just added deferred rendering for the pages that aren't drawn yet. Basically, I don't think it's going to get much faster. On my system the load when it doesn't fetch the users is only 1s. It takes about 4s when it needs to go fetch the users again.
