### ISSUE TITLE
User account delete broken

### ISSUE THREAD

**Issue by russelltsherman** [BurningFlipside/Profiles#73]
visit: https://profiles.burningflipside.com/delete.php

1st: 
toggling 'yes, i understand' does not properly disable the submit button

2nd: 
form submits to 'url: /ajax/user.php' 
i believe this should submit to /api/v1/users/[uid]

**Comment by pboyd04** [comment]
Fixed in https://github.com/BurningFlipside/Profiles/pull/81/commits/afd9f973357ee9c94e4abff08e97bcaa3fb757f6
